apiVersion: v1
kind: ConfigMap 
metadata:
  name: ironic-bmo
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
data:
  {{- $protocol := "http" }}
  {{- if  ( .Values.global.enable_tls ) }}
    {{- $protocol = "https" }}
  {{- end }}
  {{- $dnsDomain := .Values.global.dnsDomain }}      
  {{- with .Values.baremetaloperator }}      
  CACHEURL: 10.42.0.4:6180/images
  DEPLOY_KERNEL_URL: 10.42.0.4:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: 10.42.0.4:6180/images/ironic-python-agent.initramfs
  {{ if  .dhcpHosts }}
  DHCP_HOSTS: {{ .dhcpHosts }}
  {{ end }}
  DNSMASQ_BOOT_SERVER_ADDRESS: {{ tpl .bootServerAddress $ }}
  DNSMASQ_DNS_SERVER_ADDRESS: {{ tpl .dnsmasqDnsServerAddress $ }}
  HTTP_PORT: {{ .httpPort | quote }}
  {{ if .ipaBaseUri }}
  IPA_BASEURI: {{ .ipaBaseUri }}
  {{ end }}
  IRONIC_API_BASE_URL: 10.42.0.4:6385
  IRONIC_API_HOST: 10.42.0.4:6385
  IRONIC_API_HTTPD_SERVER_NAME: 10.42.0.4:6385
  IRONIC_BOOT_BASE_URL: 10.42.0.4:6180
  IRONIC_ENDPOINT: 10.42.0.4:6385/v1/
  IRONIC_INSPECTOR_BASE_URL: 10.42.0.4:5050
  IRONIC_INSPECTOR_ENDPOINT: 10.42.0.4:5050/v1/
  IRONIC_INSPECTOR_HOST: 10.42.0.4:5050
  IRONIC_INSPECTOR_HTTPD_SERVER_NAME: 10.42.0.4:5050
  IRONIC_RAMDISK_SSH_KEY: {{ .ironicRamdiskSshKey }}
  IRONIC_VMEDIA_HTTPD_SERVER_NAME: {{ tpl .bootServerAddress $ }} 
  {{- end }}
  ENABLE_PXE_BOOT: "{{ .Values.global.enable_pxe_boot }}"
  DHCP_RANGE: {{ .Values.global.dhcpRange }}
  DNSMASQ_DEFAULT_ROUTER: {{ .Values.global.dnsmasqDefaultRouter }}
  PROVISIONING_INTERFACE: {{ .Values.global.provisioningInterface }}
  PROVISIONING_IP: {{ .Values.global.provisioningIP }}
  IRONIC_INSPECTOR_VLAN_INTERFACES: all
  IRONIC_ILO_USE_SWIFT: "false"
  IRONIC_ILO_USE_WEB_SERVER_FOR_IMAGES: "true"
  IRONIC_FAST_TRACK: "true"
  IRONIC_REVERSE_PROXY_SETUP: "false"
  IRONIC_USE_MARIADB: "true"
  LISTEN_ALL_INTERFACES: "true"
  {{- if  ( .Values.global.enable_tls ) }}
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "true"
  IRONIC_KERNEL_PARAMS: console=ttyS0 suse.cafile=10.42.0.4:6180/tstcerts/ca.crt
  IPA_INSECURE: "0"
  {{- else }}
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
  IRONIC_KERNEL_PARAMS: console=ttyS0
  IPA_INSECURE: "1"
  {{- end }}
  DATABASE_HOST: {{ .Values.global.database_clusterIP }}
  #DATABASE_HOST: "127.0.0.1"
