apiVersion: v1
data:
{{- with .Values.baremetaloperator }}
  CACHEURL: http://10.25.56.129:6180/images
  DEPLOY_KERNEL_URL: http://10.25.56.129:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://10.25.56.129:6180/images/ironic-python-agent.initramfs
  HTTP_PORT: {{ .httpPort | quote }}
  IRONIC_ENDPOINT: http://10.25.56.129:6385/v1/
  IRONIC_INSPECTOR_ENDPOINT: http://10.25.56.129:5050/v1/
{{- end }}
  DHCP_RANGE: {{ .Values.global.dhcpRange }}
  PROVISIONING_INTERFACE: {{ .Values.global.provisioningInterface }}
  PROVISIONING_IP: {{ .Values.global.provisioningIP }}
  IRONIC_FAST_TRACK: "true"
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
  IRONIC_INSECURE: "true"
kind: ConfigMap
metadata:
  name: baremetal-operator-ironic
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
