apiVersion: v2
appVersion: 1.16.0
dependencies:
- alias: metal3-baremetal-operator
  name: baremetal-operator
  repository: file://./charts/baremetal-operator
- alias: metal3-ironic
  name: ironic
  repository: file://./charts/ironic
- alias: metal3-mariadb
  name: mariadb
  repository: file://./charts/mariadb
- alias: metal3-media
  condition: global.enable_metal3_media_server
  name: media
  repository: file://./charts/media
description: A Helm chart that installs all of the dependencies needed for Metal3
icon: https://github.com/cncf/artwork/raw/master/projects/metal3/icon/color/metal3-icon-color.svg
name: metal3-deploy
type: application
version: 0.2.0
